# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 100.69.158.196/backend
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeport: 1337

configuration:
  pod_directory: /usr/share/nginx/html/conf
  files:
    vertcoin.conf: |
      abc=xyz
      #a=1
      b=2
    second.conf: |
      fsdf'sd
      Fixtures.identify(:sdf'
      sdf
      'sdf
      ')


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /*

  hosts:
    - api.faldax.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 300m
   memory: 500Mi
  requests:
   cpu: 300m
   memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

controller:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 90

health:
  enable: true
  livenessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
