# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 100.69.158.196/backend
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeport: 1337

configuration:
  pod_directory: /usr/share/nginx/html/conf
  files:
    vertcoin.conf: |
      abc=xyz
      #a=1
      b=2
    second.conf: |
      fsdf'sd
      Fixtures.identify(:sdf'
      sdf
      'sdf
      ')


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:496403030999:certificate/c789b806-1990-4ff0-8e95-011a9727b80c
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /*

  hosts:
    - pre-prod-backend.faldax.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 200m
   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

controller:
  autoscaling:
    enabled: false

health:
  enable: true
  livenessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    path: /health-check
    port: 1337
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5